# Site settings
title: IoT-VN
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thủ Thuật Lập Trình, Thủ Thuật Window, Phần mềm Crack siêu an toàn, Phần mềm - Key bản quyền.



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://IoT-VN.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: MasterMind
copyright:
   name: MasterMind
   link: 'https://Fb.com/Mrlonely2512'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

#social
facebook: http://facebook.com/webjeda
quora: http://quora.com/sharathdt
twitter: http://twitter.com/@webjeda
github: http://github.com/webjeda

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

